version: "2.1"
services:
  wireguard_asgard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard_asgard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - wireguard_asgard_data:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    # network_mode: host

volumes:
  wireguard_asgard_data:
    name: wireguard_asgard_data

networks:
  default:
    name: wg_asgard
    ipam:
      config:
        - subnet: 192.168.25.0/24