version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=developement
    volumes:
      - /share/Sync/projects/weatherdatatools:/workspace:cached
    expose:
      - "8081"
    command: "npm run"
    
networks:
  default:
    external:
      name: services_bridge
