version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/holeworld/backups:/backups
      - /dockerdata:/dockerdata
    environment:
      - TZ='America/Chicago'
      - NMBD=true
      - WORKGROUP=WORKGROUP
      - PERMISSIONS=true
      - SHARE=${SHARE1}
      - SHARE1=${SHARE2}
      - USER=${USER1}
      - GLOBAL=netbios name = hydra

networks:
  default:
    external:
      name: services_bridge
