version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /share/Backups:/backups
    environment:
      - TZ='America/Chicago'
      - PERMISSIONS=true

networks:
  default:
    external:
      name: services_bridge
