version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_dhparam:/etc/nginx/dhparam
      - nginx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"

  # nginx-proxy-acme:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-proxy-acme
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - acme:/etc/acme.sh:rw
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "10"

volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_dhparam:
  nginx_certs:
#  acme:

networks:
  default:
    external:
      name: services_bridge
