version: '2'

# services:
#   nginx-proxy:
#     image: nginxproxy/nginx-proxy
#     container_name: nginx-proxy
#     restart: unless-stopped
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - nginx_conf:/etc/nginx/conf.d
#       - nginx_vhost:/etc/nginx/vhost.d
#       - nginx_html:/usr/share/nginx/html
#       - nginx_dhparam:/etc/nginx/dhparam
#       - nginx_certs:/etc/nginx/certs:ro
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "5m"
#         max-file: "10"

  # nginx-proxy-acme:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-proxy-acme
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - acme:/etc/acme.sh:rw
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "10"

# volumes:
#   nginx_conf:
#   nginx_vhost:
#   nginx_html:
#   nginx_dhparam:
#   nginx_certs:
#  acme:




services:
  # nginx:
  #   container_name: nginx
  #   image:  nginx:alpine
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: unless-stopped
  #   command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
  #   volumes:
  #     - nginx_config:/etc/nginx
  #     - nginx_www:/usr/share/nginx/html

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    # network_mode: bridge

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - /dockerdata/nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    # network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # network_mode: bridge

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  default:
    external:
      name: services_bridge
