version: "3"
    
services:
  db:
    image: mysql:5.7
    container_name: wp_mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${WP_DBROOTPW}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${WP_DBUSER}
      MYSQL_PASSWORD: ${WP_PW}
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: seizethechains.com
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8123:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WP_DBUSER}
      WORDPRESS_DB_PASSWORD: ${WP_PW}
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}
