version: "2"
services:
  axialflow:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /axialflow
    environment:
      - NODE_ENV=developement
    volumes:
      - /share/Sync/projects/axialflow:/axialflow:cached
    # expose:
    #   - "8081"
    command: "npm run"
    
networks:
  default:
    external:
      name: services_bridge
