version: '3.5'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus-linux-amd64:latest
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - etc:/etc/prometheus
    ports:
      - "9090:9090"
    environment:
      - PHP_TZ="America/Chicago"
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    command: --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/alertmanager --log.level=debug
    privileged: true
    volumes:
      - etc:/etc/alertmanager
    ports:
      - '9093:9093'
  exporter:
    image: hatamiarash7/mikrotik-exporter:latest
    container_name: mikrotik-exporter
    restart: unless-stopped
    volumes:
      - ./config/mikrotik.yml:/app/config.yml
    environment:
      - CONFIG_FILE=/app/config.yml
    ports:
      - 9436:9436

volumes:
  etc:

networks:
  default:
    external:
      name: services_bridge
