version: '3.5'
services:
  did_node:
    container_name: did_node
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:14
    command: sleep infinity 
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - /share/Sync/projects/docker-in-discord:/workspace:cached

networks:
  default:
    external:
      name: services_bridge
