version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    command: --auth
    volumes:
       - "mongodb_data:/data/db"
       - "mongodb_config:/data/configdb"
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8099:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}

volumes:
  mongodb_data:
    external: true
    name: mongodb_data
  mongodb_config:
    external: true
    name: mongodb_config

networks:
  default:
    external:
      name: services_bridge
