version: '3.3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/api.yaml

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger-editor
    ports:
      - "8002:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      URL: swagger/api.yaml

networks:
  default:
    external:
      name: services_bridge
