version: '3.2'
services:
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    privileged: true
    command:
      - '-docker_only=true'
      - '-housekeeping_interval=30s'
      - '-disable_metrics=disk'
    ports:
    - 8085:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: unless-stopped

networks:
  default:
    external:
      name: services_bridge
